[build]
  base = "client"
  publish = "client/build"
  command = "npm install && REACT_APP_BACKEND_API=https://testing.fordevio.in react-scripts build"

[context.deploy-preview]
  command = "npm install && REACT_APP_BACKEND_API=https://testing.fordevio.in react-scripts build"
